import type { FurnitureTemplate, DecorationTemplate, CeremonyStep, TodoItem } from '@/store/types';

export const FURNITURE_TEMPLATES: FurnitureTemplate[] = [
  {
    type: 'table_round',
    subtype: 'round_8',
    name: '8人圆桌',
    icon: 'Circle',
    defaultPrice: 800,
    defaultColor: '#FFFFFF',
    width: 120,
    height: 120,
  },
  {
    type: 'table_round',
    subtype: 'round_10',
    name: '10人圆桌',
    icon: 'Circle',
    defaultPrice: 1000,
    defaultColor: '#FFFFFF',
    width: 140,
    height: 140,
  },
  {
    type: 'table_round',
    subtype: 'round_12',
    name: '12人圆桌',
    icon: 'Circle',
    defaultPrice: 1200,
    defaultColor: '#FFFFFF',
    width: 160,
    height: 160,
  },
  {
    type: 'table_long',
    subtype: 'long_6',
    name: '6人长桌',
    icon: 'RectangleHorizontal',
    defaultPrice: 600,
    defaultColor: '#F5E6E0',
    width: 180,
    height: 80,
  },
  {
    type: 'table_long',
    subtype: 'long_8',
    name: '8人长桌',
    icon: 'RectangleHorizontal',
    defaultPrice: 800,
    defaultColor: '#F5E6E0',
    width: 240,
    height: 80,
  },
  {
    type: 'chair',
    subtype: 'chiavari',
    name: '竹节椅',
    icon: 'Armchair',
    defaultPrice: 80,
    defaultColor: '#E8C4A0',
    width: 40,
    height: 40,
  },
  {
    type: 'chair',
    subtype: 'white',
    name: '白色宴会椅',
    icon: 'Armchair',
    defaultPrice: 60,
    defaultColor: '#FFFFFF',
    width: 40,
    height: 40,
  },
  {
    type: 'chair',
    subtype: 'gold',
    name: '金色贵宾椅',
    icon: 'Crown',
    defaultPrice: 120,
    defaultColor: '#C9A961',
    width: 45,
    height: 45,
  },
  {
    type: 'podium',
    subtype: 'classic',
    name: '经典司仪台',
    icon: 'Podium',
    defaultPrice: 500,
    defaultColor: '#C9A961',
    width: 60,
    height: 100,
  },
  {
    type: 'podium',
    subtype: 'modern',
    name: '现代司仪台',
    icon: 'Podium',
    defaultPrice: 600,
    defaultColor: '#FFFFFF',
    width: 70,
    height: 110,
  },
  {
    type: 'flower',
    subtype: 'centerpiece',
    name: '桌花花艺',
    icon: 'Flower2',
    defaultPrice: 300,
    defaultColor: '#FFB6C1',
    width: 30,
    height: 30,
  },
  {
    type: 'light',
    subtype: 'table_lamp',
    name: '桌面台灯',
    icon: 'Lamp',
    defaultPrice: 150,
    defaultColor: '#FFE4B5',
    width: 25,
    height: 25,
  },
];

export const DECORATION_TEMPLATES: DecorationTemplate[] = [
  {
    type: 'flower_arrangement',
    style: 'peonies',
    name: '牡丹花束',
    icon: 'Flower2',
    defaultPrice: 500,
    defaultColor: '#FFB6C1',
  },
  {
    type: 'flower_arrangement',
    style: 'roses',
    name: '玫瑰花艺',
    icon: 'Flower2',
    defaultPrice: 400,
    defaultColor: '#FF69B4',
  },
  {
    type: 'flower_arrangement',
    style: 'hydrangea',
    name: '绣球花艺',
    icon: 'Flower2',
    defaultPrice: 450,
    defaultColor: '#E6E6FA',
  },
  {
    type: 'lantern',
    style: 'paper',
    name: '纸灯笼',
    icon: 'Lamp',
    defaultPrice: 80,
    defaultColor: '#FF6B6B',
  },
  {
    type: 'lantern',
    style: 'moroccan',
    name: '摩洛哥灯',
    icon: 'Lightbulb',
    defaultPrice: 200,
    defaultColor: '#FFD700',
  },
  {
    type: 'arch',
    style: 'flower_arch',
    name: '鲜花拱门',
    icon: 'Archway',
    defaultPrice: 3000,
    defaultColor: '#FFB6C1',
  },
  {
    type: 'arch',
    style: 'balloon_arch',
    name: '气球拱门',
    icon: 'Archway',
    defaultPrice: 1500,
    defaultColor: '#FFC0CB',
  },
  {
    type: 'candle',
    style: 'pillar',
    name: '柱状蜡烛',
    icon: 'Candle',
    defaultPrice: 50,
    defaultColor: '#FFFACD',
  },
  {
    type: 'candle',
    style: 'tealight',
    name: '茶蜡烛台',
    icon: 'Flame',
    defaultPrice: 30,
    defaultColor: '#FFE4B5',
  },
  {
    type: 'light_string',
    style: 'fairy',
    name: '星星灯串',
    icon: 'Sparkles',
    defaultPrice: 200,
    defaultColor: '#FFD700',
  },
];

export const DEFAULT_CEREMONY_STEPS: CeremonyStep[] = [
  {
    id: 'step-1',
    title: '新人入场',
    description: '伴随着婚礼进行曲，新郎新娘步入婚礼殿堂',
    durationMin: 5,
    order: 1,
    host: '司仪',
    icon: 'Heart',
  },
  {
    id: 'step-2',
    title: '证婚人致辞',
    description: '证婚人上台发表证婚致辞',
    durationMin: 8,
    order: 2,
    host: '证婚人',
    icon: 'FileText',
  },
  {
    id: 'step-3',
    title: '交换戒指',
    description: '新人互相交换结婚戒指，许下爱的承诺',
    durationMin: 5,
    order: 3,
    host: '司仪',
    icon: 'CircleDot',
  },
  {
    id: 'step-4',
    title: '亲吻新娘',
    description: '新郎掀开新娘头纱，深情一吻',
    durationMin: 3,
    order: 4,
    host: '司仪',
    icon: 'Heart',
  },
  {
    id: 'step-5',
    title: '父母致辞',
    description: '双方父母上台发表感言',
    durationMin: 10,
    order: 5,
    host: '双方父母',
    icon: 'Users',
  },
  {
    id: 'step-6',
    title: '新人敬酒',
    description: '新人向宾客敬酒致谢',
    durationMin: 20,
    order: 6,
    host: '新人',
    icon: 'Wine',
  },
  {
    id: 'step-7',
    title: '抛捧花',
    description: '新娘抛捧花，传递幸福',
    durationMin: 5,
    order: 7,
    host: '司仪',
    icon: 'Flower2',
  },
  {
    id: 'step-8',
    title: '婚礼礼成',
    description: '婚礼仪式圆满结束，新人退场',
    durationMin: 5,
    order: 8,
    host: '司仪',
    icon: 'PartyPopper',
  },
];

export const DEFAULT_TODOS: TodoItem[] = [
  { id: 'todo-1', title: '确定婚礼场地', completed: false, category: 'venue' },
  { id: 'todo-2', title: '布置宾客座位图', completed: false, category: 'seating' },
  { id: 'todo-3', title: '配置舞台和T台', completed: false, category: 'stage' },
  { id: 'todo-4', title: '上传新人照片', completed: false, category: 'stage' },
  { id: 'todo-5', title: '添加花艺装饰', completed: false, category: 'decoration' },
  { id: 'todo-6', title: '设计灯光效果', completed: false, category: 'decoration' },
  { id: 'todo-7', title: '确认背景音乐', completed: false, category: 'decoration' },
  { id: 'todo-8', title: '编辑仪式流程', completed: false, category: 'ceremony' },
  { id: 'todo-9', title: '导入宾客名单', completed: false, category: 'seating' },
  { id: 'todo-10', title: '规划入场路线', completed: false, category: 'seating' },
];

export const SCENE_BACKGROUNDS = {
  island: {
    day: 'linear-gradient(180deg, #87CEEB 0%, #E0F6FF 30%, #F5DEB3 70%, #DEB887 100%)',
    night: 'linear-gradient(180deg, #0D1B2A 0%, #1B263B 40%, #2D3A4A 70%, #3D4A5A 100%)',
  },
  garden: {
    day: 'linear-gradient(180deg, #B8E6B8 0%, #90EE90 30%, #98D8AA 60%, #7CB342 100%)',
    night: 'linear-gradient(180deg, #1A2F1A 0%, #2D4A2D 40%, #3D5A3D 70%, #4A6B4A 100%)',
  },
};

export const SCENE_NAMES: Record<string, string> = {
  island: '海岛婚礼',
  garden: '花园婚礼',
};

export const TIME_MODE_NAMES: Record<string, string> = {
  day: '白天',
  night: '夜晚',
};

export const FURNITURE_CATEGORIES = [
  { key: 'table_round', name: '圆桌', icon: 'Circle' },
  { key: 'table_long', name: '长桌', icon: 'RectangleHorizontal' },
  { key: 'chair', name: '椅子', icon: 'Armchair' },
  { key: 'podium', name: '司仪台', icon: 'Podium' },
];

export const DECORATION_CATEGORIES = [
  { key: 'flower_arrangement', name: '花艺', icon: 'Flower2' },
  { key: 'lantern', name: '灯笼', icon: 'Lamp' },
  { key: 'arch', name: '拱门', icon: 'Archway' },
  { key: 'candle', name: '蜡烛', icon: 'Candle' },
  { key: 'light_string', name: '灯串', icon: 'Sparkles' },
];
